export const RoutePaths = {
    HOME: '/',
    ALTERNATIVE_EDGE: '/alternative-edge',
    UNCRIDERS: '/uncriders',
    ADVANCED_GEAR: '/advanced-gear',
    PRODUCT_DETAILS: '/product/:productId',
    CATALOG: '/catalog',
    ALBUM: '/album',
    CONTACTS: '/contacts',
    PRIVACY: '/privacy',
    CARE: '/care',
    NOT_FOUND: '/not-found',
    ADMIN_CATALOG: '/admin/catalog',
    ORDER: '/order',
    ADMIN_ORDERS: '/admin/orders',
}