spring:
  datasource:
    password: 1954623790
    username: postgres
    url: jdbc:postgresql://localhost:5432/online_clothes_store
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
jwt:

  access-token-key: '{"kty": "oct", "k": "kL9yZ1mB5aV4bU7vH4mO0wN5hT3cL6gP2xV1cU5wA7oH9xV7qW8oA6hG5bU4l"}'
  refresh-token-key: '{"kty": "oct", "k": "mN8jEh4pWz9sVxGyQ3cA7bL2uR1oH0Kf"}'
  #  m - minutes
  #  h - hours
  #  d - days
  access-token-expiration: "15d"
  refresh-token-expiration: "30d"

logging:
  level:
    org.springframework.security: trace
